version: 2
updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "weekly"
        versioning-strategy: lockfile-only
        groups:
            Npm-dependencies:
                patterns:
                    - "*"
